// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/fachebot/evm-grid-bot/internal/ent/nonce"
	"github.com/fachebot/evm-grid-bot/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NonceUpdate is the builder for updating Nonce entities.
type NonceUpdate struct {
	config
	hooks    []Hook
	mutation *NonceMutation
}

// Where appends a list predicates to the NonceUpdate builder.
func (_u *NonceUpdate) Where(ps ...predicate.Nonce) *NonceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *NonceUpdate) SetUpdateTime(v time.Time) *NonceUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetAccount sets the "account" field.
func (_u *NonceUpdate) SetAccount(v string) *NonceUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *NonceUpdate) SetNillableAccount(v *string) *NonceUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *NonceUpdate) SetNonce(v uint64) *NonceUpdate {
	_u.mutation.ResetNonce()
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *NonceUpdate) SetNillableNonce(v *uint64) *NonceUpdate {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// AddNonce adds value to the "nonce" field.
func (_u *NonceUpdate) AddNonce(v int64) *NonceUpdate {
	_u.mutation.AddNonce(v)
	return _u
}

// Mutation returns the NonceMutation object of the builder.
func (_u *NonceUpdate) Mutation() *NonceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NonceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NonceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NonceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NonceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NonceUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := nonce.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NonceUpdate) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := nonce.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Nonce.account": %w`, err)}
		}
	}
	return nil
}

func (_u *NonceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nonce.Table, nonce.Columns, sqlgraph.NewFieldSpec(nonce.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(nonce.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(nonce.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(nonce.FieldNonce, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedNonce(); ok {
		_spec.AddField(nonce.FieldNonce, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nonce.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NonceUpdateOne is the builder for updating a single Nonce entity.
type NonceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NonceMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *NonceUpdateOne) SetUpdateTime(v time.Time) *NonceUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetAccount sets the "account" field.
func (_u *NonceUpdateOne) SetAccount(v string) *NonceUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *NonceUpdateOne) SetNillableAccount(v *string) *NonceUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *NonceUpdateOne) SetNonce(v uint64) *NonceUpdateOne {
	_u.mutation.ResetNonce()
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *NonceUpdateOne) SetNillableNonce(v *uint64) *NonceUpdateOne {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// AddNonce adds value to the "nonce" field.
func (_u *NonceUpdateOne) AddNonce(v int64) *NonceUpdateOne {
	_u.mutation.AddNonce(v)
	return _u
}

// Mutation returns the NonceMutation object of the builder.
func (_u *NonceUpdateOne) Mutation() *NonceMutation {
	return _u.mutation
}

// Where appends a list predicates to the NonceUpdate builder.
func (_u *NonceUpdateOne) Where(ps ...predicate.Nonce) *NonceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NonceUpdateOne) Select(field string, fields ...string) *NonceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Nonce entity.
func (_u *NonceUpdateOne) Save(ctx context.Context) (*Nonce, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NonceUpdateOne) SaveX(ctx context.Context) *Nonce {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NonceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NonceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NonceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := nonce.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NonceUpdateOne) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := nonce.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Nonce.account": %w`, err)}
		}
	}
	return nil
}

func (_u *NonceUpdateOne) sqlSave(ctx context.Context) (_node *Nonce, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nonce.Table, nonce.Columns, sqlgraph.NewFieldSpec(nonce.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Nonce.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nonce.FieldID)
		for _, f := range fields {
			if !nonce.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nonce.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(nonce.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(nonce.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(nonce.FieldNonce, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedNonce(); ok {
		_spec.AddField(nonce.FieldNonce, field.TypeUint64, value)
	}
	_node = &Nonce{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nonce.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
