// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/fachebot/evm-grid-bot/internal/ent/predicate"
	"github.com/fachebot/evm-grid-bot/internal/ent/settings"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SettingsUpdate) SetUpdateTime(v time.Time) *SettingsUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *SettingsUpdate) SetUserId(v int64) *SettingsUpdate {
	_u.mutation.ResetUserId()
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableUserId(v *int64) *SettingsUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// AddUserId adds value to the "userId" field.
func (_u *SettingsUpdate) AddUserId(v int64) *SettingsUpdate {
	_u.mutation.AddUserId(v)
	return _u
}

// SetSlippageBps sets the "slippageBps" field.
func (_u *SettingsUpdate) SetSlippageBps(v int) *SettingsUpdate {
	_u.mutation.ResetSlippageBps()
	_u.mutation.SetSlippageBps(v)
	return _u
}

// SetNillableSlippageBps sets the "slippageBps" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableSlippageBps(v *int) *SettingsUpdate {
	if v != nil {
		_u.SetSlippageBps(*v)
	}
	return _u
}

// AddSlippageBps adds value to the "slippageBps" field.
func (_u *SettingsUpdate) AddSlippageBps(v int) *SettingsUpdate {
	_u.mutation.AddSlippageBps(v)
	return _u
}

// SetSellSlippageBps sets the "sellSlippageBps" field.
func (_u *SettingsUpdate) SetSellSlippageBps(v int) *SettingsUpdate {
	_u.mutation.ResetSellSlippageBps()
	_u.mutation.SetSellSlippageBps(v)
	return _u
}

// SetNillableSellSlippageBps sets the "sellSlippageBps" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableSellSlippageBps(v *int) *SettingsUpdate {
	if v != nil {
		_u.SetSellSlippageBps(*v)
	}
	return _u
}

// AddSellSlippageBps adds value to the "sellSlippageBps" field.
func (_u *SettingsUpdate) AddSellSlippageBps(v int) *SettingsUpdate {
	_u.mutation.AddSellSlippageBps(v)
	return _u
}

// ClearSellSlippageBps clears the value of the "sellSlippageBps" field.
func (_u *SettingsUpdate) ClearSellSlippageBps() *SettingsUpdate {
	_u.mutation.ClearSellSlippageBps()
	return _u
}

// SetExitSlippageBps sets the "exitSlippageBps" field.
func (_u *SettingsUpdate) SetExitSlippageBps(v int) *SettingsUpdate {
	_u.mutation.ResetExitSlippageBps()
	_u.mutation.SetExitSlippageBps(v)
	return _u
}

// SetNillableExitSlippageBps sets the "exitSlippageBps" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableExitSlippageBps(v *int) *SettingsUpdate {
	if v != nil {
		_u.SetExitSlippageBps(*v)
	}
	return _u
}

// AddExitSlippageBps adds value to the "exitSlippageBps" field.
func (_u *SettingsUpdate) AddExitSlippageBps(v int) *SettingsUpdate {
	_u.mutation.AddExitSlippageBps(v)
	return _u
}

// ClearExitSlippageBps clears the value of the "exitSlippageBps" field.
func (_u *SettingsUpdate) ClearExitSlippageBps() *SettingsUpdate {
	_u.mutation.ClearExitSlippageBps()
	return _u
}

// SetDexAggregator sets the "dexAggregator" field.
func (_u *SettingsUpdate) SetDexAggregator(v settings.DexAggregator) *SettingsUpdate {
	_u.mutation.SetDexAggregator(v)
	return _u
}

// SetNillableDexAggregator sets the "dexAggregator" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableDexAggregator(v *settings.DexAggregator) *SettingsUpdate {
	if v != nil {
		_u.SetDexAggregator(*v)
	}
	return _u
}

// SetEnableInfiniteApproval sets the "enableInfiniteApproval" field.
func (_u *SettingsUpdate) SetEnableInfiniteApproval(v bool) *SettingsUpdate {
	_u.mutation.SetEnableInfiniteApproval(v)
	return _u
}

// SetNillableEnableInfiniteApproval sets the "enableInfiniteApproval" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableEnableInfiniteApproval(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetEnableInfiniteApproval(*v)
	}
	return _u
}

// ClearEnableInfiniteApproval clears the value of the "enableInfiniteApproval" field.
func (_u *SettingsUpdate) ClearEnableInfiniteApproval() *SettingsUpdate {
	_u.mutation.ClearEnableInfiniteApproval()
	return _u
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdate) Mutation() *SettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := settings.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettingsUpdate) check() error {
	if v, ok := _u.mutation.SlippageBps(); ok {
		if err := settings.SlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "slippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.slippageBps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SellSlippageBps(); ok {
		if err := settings.SellSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "sellSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.sellSlippageBps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitSlippageBps(); ok {
		if err := settings.ExitSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "exitSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.exitSlippageBps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DexAggregator(); ok {
		if err := settings.DexAggregatorValidator(v); err != nil {
			return &ValidationError{Name: "dexAggregator", err: fmt.Errorf(`ent: validator failed for field "Settings.dexAggregator": %w`, err)}
		}
	}
	return nil
}

func (_u *SettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(settings.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserId(); ok {
		_spec.SetField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserId(); ok {
		_spec.AddField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SlippageBps(); ok {
		_spec.SetField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlippageBps(); ok {
		_spec.AddField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SellSlippageBps(); ok {
		_spec.SetField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSellSlippageBps(); ok {
		_spec.AddField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if _u.mutation.SellSlippageBpsCleared() {
		_spec.ClearField(settings.FieldSellSlippageBps, field.TypeInt)
	}
	if value, ok := _u.mutation.ExitSlippageBps(); ok {
		_spec.SetField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitSlippageBps(); ok {
		_spec.AddField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if _u.mutation.ExitSlippageBpsCleared() {
		_spec.ClearField(settings.FieldExitSlippageBps, field.TypeInt)
	}
	if value, ok := _u.mutation.DexAggregator(); ok {
		_spec.SetField(settings.FieldDexAggregator, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EnableInfiniteApproval(); ok {
		_spec.SetField(settings.FieldEnableInfiniteApproval, field.TypeBool, value)
	}
	if _u.mutation.EnableInfiniteApprovalCleared() {
		_spec.ClearField(settings.FieldEnableInfiniteApproval, field.TypeBool)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *SettingsUpdateOne) SetUpdateTime(v time.Time) *SettingsUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *SettingsUpdateOne) SetUserId(v int64) *SettingsUpdateOne {
	_u.mutation.ResetUserId()
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableUserId(v *int64) *SettingsUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// AddUserId adds value to the "userId" field.
func (_u *SettingsUpdateOne) AddUserId(v int64) *SettingsUpdateOne {
	_u.mutation.AddUserId(v)
	return _u
}

// SetSlippageBps sets the "slippageBps" field.
func (_u *SettingsUpdateOne) SetSlippageBps(v int) *SettingsUpdateOne {
	_u.mutation.ResetSlippageBps()
	_u.mutation.SetSlippageBps(v)
	return _u
}

// SetNillableSlippageBps sets the "slippageBps" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableSlippageBps(v *int) *SettingsUpdateOne {
	if v != nil {
		_u.SetSlippageBps(*v)
	}
	return _u
}

// AddSlippageBps adds value to the "slippageBps" field.
func (_u *SettingsUpdateOne) AddSlippageBps(v int) *SettingsUpdateOne {
	_u.mutation.AddSlippageBps(v)
	return _u
}

// SetSellSlippageBps sets the "sellSlippageBps" field.
func (_u *SettingsUpdateOne) SetSellSlippageBps(v int) *SettingsUpdateOne {
	_u.mutation.ResetSellSlippageBps()
	_u.mutation.SetSellSlippageBps(v)
	return _u
}

// SetNillableSellSlippageBps sets the "sellSlippageBps" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableSellSlippageBps(v *int) *SettingsUpdateOne {
	if v != nil {
		_u.SetSellSlippageBps(*v)
	}
	return _u
}

// AddSellSlippageBps adds value to the "sellSlippageBps" field.
func (_u *SettingsUpdateOne) AddSellSlippageBps(v int) *SettingsUpdateOne {
	_u.mutation.AddSellSlippageBps(v)
	return _u
}

// ClearSellSlippageBps clears the value of the "sellSlippageBps" field.
func (_u *SettingsUpdateOne) ClearSellSlippageBps() *SettingsUpdateOne {
	_u.mutation.ClearSellSlippageBps()
	return _u
}

// SetExitSlippageBps sets the "exitSlippageBps" field.
func (_u *SettingsUpdateOne) SetExitSlippageBps(v int) *SettingsUpdateOne {
	_u.mutation.ResetExitSlippageBps()
	_u.mutation.SetExitSlippageBps(v)
	return _u
}

// SetNillableExitSlippageBps sets the "exitSlippageBps" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableExitSlippageBps(v *int) *SettingsUpdateOne {
	if v != nil {
		_u.SetExitSlippageBps(*v)
	}
	return _u
}

// AddExitSlippageBps adds value to the "exitSlippageBps" field.
func (_u *SettingsUpdateOne) AddExitSlippageBps(v int) *SettingsUpdateOne {
	_u.mutation.AddExitSlippageBps(v)
	return _u
}

// ClearExitSlippageBps clears the value of the "exitSlippageBps" field.
func (_u *SettingsUpdateOne) ClearExitSlippageBps() *SettingsUpdateOne {
	_u.mutation.ClearExitSlippageBps()
	return _u
}

// SetDexAggregator sets the "dexAggregator" field.
func (_u *SettingsUpdateOne) SetDexAggregator(v settings.DexAggregator) *SettingsUpdateOne {
	_u.mutation.SetDexAggregator(v)
	return _u
}

// SetNillableDexAggregator sets the "dexAggregator" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableDexAggregator(v *settings.DexAggregator) *SettingsUpdateOne {
	if v != nil {
		_u.SetDexAggregator(*v)
	}
	return _u
}

// SetEnableInfiniteApproval sets the "enableInfiniteApproval" field.
func (_u *SettingsUpdateOne) SetEnableInfiniteApproval(v bool) *SettingsUpdateOne {
	_u.mutation.SetEnableInfiniteApproval(v)
	return _u
}

// SetNillableEnableInfiniteApproval sets the "enableInfiniteApproval" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableEnableInfiniteApproval(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetEnableInfiniteApproval(*v)
	}
	return _u
}

// ClearEnableInfiniteApproval clears the value of the "enableInfiniteApproval" field.
func (_u *SettingsUpdateOne) ClearEnableInfiniteApproval() *SettingsUpdateOne {
	_u.mutation.ClearEnableInfiniteApproval()
	return _u
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdateOne) Mutation() *SettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Settings entity.
func (_u *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := settings.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettingsUpdateOne) check() error {
	if v, ok := _u.mutation.SlippageBps(); ok {
		if err := settings.SlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "slippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.slippageBps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SellSlippageBps(); ok {
		if err := settings.SellSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "sellSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.sellSlippageBps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitSlippageBps(); ok {
		if err := settings.ExitSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "exitSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.exitSlippageBps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DexAggregator(); ok {
		if err := settings.DexAggregatorValidator(v); err != nil {
			return &ValidationError{Name: "dexAggregator", err: fmt.Errorf(`ent: validator failed for field "Settings.dexAggregator": %w`, err)}
		}
	}
	return nil
}

func (_u *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(settings.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserId(); ok {
		_spec.SetField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserId(); ok {
		_spec.AddField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SlippageBps(); ok {
		_spec.SetField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlippageBps(); ok {
		_spec.AddField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SellSlippageBps(); ok {
		_spec.SetField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSellSlippageBps(); ok {
		_spec.AddField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if _u.mutation.SellSlippageBpsCleared() {
		_spec.ClearField(settings.FieldSellSlippageBps, field.TypeInt)
	}
	if value, ok := _u.mutation.ExitSlippageBps(); ok {
		_spec.SetField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitSlippageBps(); ok {
		_spec.AddField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if _u.mutation.ExitSlippageBpsCleared() {
		_spec.ClearField(settings.FieldExitSlippageBps, field.TypeInt)
	}
	if value, ok := _u.mutation.DexAggregator(); ok {
		_spec.SetField(settings.FieldDexAggregator, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EnableInfiniteApproval(); ok {
		_spec.SetField(settings.FieldEnableInfiniteApproval, field.TypeBool, value)
	}
	if _u.mutation.EnableInfiniteApprovalCleared() {
		_spec.ClearField(settings.FieldEnableInfiniteApproval, field.TypeBool)
	}
	_node = &Settings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
