// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/fachebot/evm-grid-bot/internal/ent/settings"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SettingsCreate is the builder for creating a Settings entity.
type SettingsCreate struct {
	config
	mutation *SettingsMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *SettingsCreate) SetCreateTime(v time.Time) *SettingsCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableCreateTime(v *time.Time) *SettingsCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SettingsCreate) SetUpdateTime(v time.Time) *SettingsCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableUpdateTime(v *time.Time) *SettingsCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetUserId sets the "userId" field.
func (_c *SettingsCreate) SetUserId(v int64) *SettingsCreate {
	_c.mutation.SetUserId(v)
	return _c
}

// SetSlippageBps sets the "slippageBps" field.
func (_c *SettingsCreate) SetSlippageBps(v int) *SettingsCreate {
	_c.mutation.SetSlippageBps(v)
	return _c
}

// SetSellSlippageBps sets the "sellSlippageBps" field.
func (_c *SettingsCreate) SetSellSlippageBps(v int) *SettingsCreate {
	_c.mutation.SetSellSlippageBps(v)
	return _c
}

// SetNillableSellSlippageBps sets the "sellSlippageBps" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableSellSlippageBps(v *int) *SettingsCreate {
	if v != nil {
		_c.SetSellSlippageBps(*v)
	}
	return _c
}

// SetExitSlippageBps sets the "exitSlippageBps" field.
func (_c *SettingsCreate) SetExitSlippageBps(v int) *SettingsCreate {
	_c.mutation.SetExitSlippageBps(v)
	return _c
}

// SetNillableExitSlippageBps sets the "exitSlippageBps" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableExitSlippageBps(v *int) *SettingsCreate {
	if v != nil {
		_c.SetExitSlippageBps(*v)
	}
	return _c
}

// SetDexAggregator sets the "dexAggregator" field.
func (_c *SettingsCreate) SetDexAggregator(v settings.DexAggregator) *SettingsCreate {
	_c.mutation.SetDexAggregator(v)
	return _c
}

// SetEnableInfiniteApproval sets the "enableInfiniteApproval" field.
func (_c *SettingsCreate) SetEnableInfiniteApproval(v bool) *SettingsCreate {
	_c.mutation.SetEnableInfiniteApproval(v)
	return _c
}

// SetNillableEnableInfiniteApproval sets the "enableInfiniteApproval" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableEnableInfiniteApproval(v *bool) *SettingsCreate {
	if v != nil {
		_c.SetEnableInfiniteApproval(*v)
	}
	return _c
}

// Mutation returns the SettingsMutation object of the builder.
func (_c *SettingsCreate) Mutation() *SettingsMutation {
	return _c.mutation
}

// Save creates the Settings in the database.
func (_c *SettingsCreate) Save(ctx context.Context) (*Settings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettingsCreate) SaveX(ctx context.Context) *Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SettingsCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := settings.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := settings.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettingsCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Settings.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Settings.update_time"`)}
	}
	if _, ok := _c.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New(`ent: missing required field "Settings.userId"`)}
	}
	if _, ok := _c.mutation.SlippageBps(); !ok {
		return &ValidationError{Name: "slippageBps", err: errors.New(`ent: missing required field "Settings.slippageBps"`)}
	}
	if v, ok := _c.mutation.SlippageBps(); ok {
		if err := settings.SlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "slippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.slippageBps": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SellSlippageBps(); ok {
		if err := settings.SellSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "sellSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.sellSlippageBps": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitSlippageBps(); ok {
		if err := settings.ExitSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "exitSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.exitSlippageBps": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DexAggregator(); !ok {
		return &ValidationError{Name: "dexAggregator", err: errors.New(`ent: missing required field "Settings.dexAggregator"`)}
	}
	if v, ok := _c.mutation.DexAggregator(); ok {
		if err := settings.DexAggregatorValidator(v); err != nil {
			return &ValidationError{Name: "dexAggregator", err: fmt.Errorf(`ent: validator failed for field "Settings.dexAggregator": %w`, err)}
		}
	}
	return nil
}

func (_c *SettingsCreate) sqlSave(ctx context.Context) (*Settings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettingsCreate) createSpec() (*Settings, *sqlgraph.CreateSpec) {
	var (
		_node = &Settings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(settings.Table, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(settings.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(settings.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.UserId(); ok {
		_spec.SetField(settings.FieldUserId, field.TypeInt64, value)
		_node.UserId = value
	}
	if value, ok := _c.mutation.SlippageBps(); ok {
		_spec.SetField(settings.FieldSlippageBps, field.TypeInt, value)
		_node.SlippageBps = value
	}
	if value, ok := _c.mutation.SellSlippageBps(); ok {
		_spec.SetField(settings.FieldSellSlippageBps, field.TypeInt, value)
		_node.SellSlippageBps = &value
	}
	if value, ok := _c.mutation.ExitSlippageBps(); ok {
		_spec.SetField(settings.FieldExitSlippageBps, field.TypeInt, value)
		_node.ExitSlippageBps = &value
	}
	if value, ok := _c.mutation.DexAggregator(); ok {
		_spec.SetField(settings.FieldDexAggregator, field.TypeEnum, value)
		_node.DexAggregator = value
	}
	if value, ok := _c.mutation.EnableInfiniteApproval(); ok {
		_spec.SetField(settings.FieldEnableInfiniteApproval, field.TypeBool, value)
		_node.EnableInfiniteApproval = &value
	}
	return _node, _spec
}

// SettingsCreateBulk is the builder for creating many Settings entities in bulk.
type SettingsCreateBulk struct {
	config
	err      error
	builders []*SettingsCreate
}

// Save creates the Settings entities in the database.
func (_c *SettingsCreateBulk) Save(ctx context.Context) ([]*Settings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Settings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettingsCreateBulk) SaveX(ctx context.Context) []*Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
